@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Jul 05 14:04:12 -0500 2022
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim coincidence_behavior_behav -key {Behavioral:sim_1:Functional:coincidence_behavior} -tclbatch coincidence_behavior.tcl -view C:/redpitaya_guide-master/projects/pet_scan/pet_controller/threshold_sim_behav.wcfg -view C:/redpitaya_guide-master/projects/pet_scan/pet_controller/pet_controller.sim/Coincidence_behav.wcfg -log simulate.log"
call xsim  coincidence_behavior_behav -key {Behavioral:sim_1:Functional:coincidence_behavior} -tclbatch coincidence_behavior.tcl -view C:/redpitaya_guide-master/projects/pet_scan/pet_controller/threshold_sim_behav.wcfg -view C:/redpitaya_guide-master/projects/pet_scan/pet_controller/pet_controller.sim/Coincidence_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
