# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA/FromScratch/FromScratch.srcs/sources_1/bd/system/ip/system_axi_gpio_0_9/system_axi_gpio_0_9.xci
# IP: The module: 'system_axi_gpio_0_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/FromScratch/FromScratch.gen/sources_1/bd/system/ip/system_axi_gpio_0_9/system_axi_gpio_0_9_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_9'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/FromScratch/FromScratch.gen/sources_1/bd/system/ip/system_axi_gpio_0_9/system_axi_gpio_0_9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/FromScratch/FromScratch.gen/sources_1/bd/system/ip/system_axi_gpio_0_9/system_axi_gpio_0_9.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/FPGA/FromScratch/FromScratch.srcs/sources_1/bd/system/ip/system_axi_gpio_0_9/system_axi_gpio_0_9.xci
# IP: The module: 'system_axi_gpio_0_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/FromScratch/FromScratch.gen/sources_1/bd/system/ip/system_axi_gpio_0_9/system_axi_gpio_0_9_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/FromScratch/FromScratch.gen/sources_1/bd/system/ip/system_axi_gpio_0_9/system_axi_gpio_0_9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/FromScratch/FromScratch.gen/sources_1/bd/system/ip/system_axi_gpio_0_9/system_axi_gpio_0_9.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
